### ISSUE TITLE
[TECH ED] Build todo-list app

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Module-JS2#64]
### Link to the coursework

Look up the `todo-list` app in the `week-3` directory to get started.

### Why are we doing this?

These challenges are designed to develop your problem-solving skills.

## Acceptance criteria

- [ ] Given a todo list web application
When the page loads
Then the populateTodoList() function should create todo list items for each hardcoded todo
When a todo list item is created
Then it should contain: ☑ 🗑  todo text
When the checkbox icon is clicked
Then the todo text should have strikethrough 
And the checkbox should be ticked ✅ 🗑  ~todo text~

- [ ] Given a todo list item on the page
When the trash icon is clicked
Then the todo list item should be deleted

- [ ] Given a button to add new todos
When the button is clicked
Then a new todo should be added to the list with the checkbox and trash icons

- [ ] Given a button to mass delete completed todos
When the button is clicked
Then any todos that have been checked off should be deleted

- [ ] Given the ability to set a deadline when creating a todo
When a deadline is set
Then the deadline should be displayed next to the todo text

### Maximum time in hours

4

### How to get help

Share your blockers in your class channel
https://syllabus.codeyourfuture.io/guides/asking-questions

### How to submit

1. Fork to your Github account.
2. Make a branch for this project.
3. Make regular small commits in this branch with clear messages.
4. When you are ready, open a PR to the CYF repo, following the instructions in the PR template.

```mermaid
gitGraph
    commit id: "start"
    branch feature/todo-list
     commit id: "skeleton page code"
    commit id: "list container"
    commit id: "single todo item"
    commit id: "manage icon states"
    commit id: "desktop layout"
    commit id: "lighthouse audit revisions desktop"
    checkout main
    merge feature/todo-list
```

There are several projects in this repo. [Make a new branch](https://simpledev.io/lesson/create-branch-gh-desktop-1) for each project.
